# basic options
title: Seasons Landscape
author: Steven Straub
email: test@domain.com
description: A wonderful site
twitter_username: test1
github_username:  test2

# Build settings
markdown: kramdown
theme: minima
